# Generated by Django 3.1.1 on 2020-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mem', models.CharField(max_length=300)),
                ('title_mem', models.CharField(max_length=150)),
                ('about_mem', models.CharField(max_length=1500)),
                ('image_mem', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pioneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=1500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
